# Generated by Django 2.1.7 on 2019-03-30 02:38

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('P', 'Protein'), ('G', 'Grain'), ('F', 'Fruit'), ('V', 'Vegetable'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ingred_list', models.TextField(max_length=1500)),
                ('simple_ingred_list', models.TextField(max_length=1500)),
                ('instructions', models.TextField(max_length=2500)),
                ('num_ingreds', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
