# Generated by Django 2.1.7 on 2019-03-09 18:56

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('completemyrecipe', '0002_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingred_list',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=2500),
        ),
    ]
